contact_links:
  - name: Общение / Communication
    url: https://github.com/makriq-org/FlClashM/issues
    about: Сообщить о проблеме или обсудить поведение клиента / Report an issue or discuss client behavior
