display_name: FlClashM

packager: makriq-org
packagerEmail: 141617622+makriq@users.noreply.github.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - FlClashM
  - Clash
    - Proxy

generic_name: FlClashM

group: Applications/Internet

startup_notify: true
