display_name: FlClashM
package_name: app.flclashm.client

icon: ./assets/images/icon.png

keywords:
  - FlClashM
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClashM

categories:
  - Network

startup_notify: true

include: []
