display_name: FlClashM
package_name: app.flclashm.client
maintainer:
  name: makriq-org
  email: 141617622+makriq@users.noreply.github.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - FlClashM
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClashM

categories:
  - Network

startup_notify: true
