script_template: inno_setup.iss
app_id: app.flclashm.client
app_name: FlClashM
publisher: pluralplay
publisher_url: https://github.com/makriq-org/FlClashM
display_name: FlClashM
executable_name: FlClashM.exe
output_base_file_name: FlClashM.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: ru
  - lang: en
privileges_required: admin
